application: egaxegax
version: 1
runtime: python27
api_version: 1
threadsafe: no

builtins:
- remote_api: on

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /media
  static_dir: media/
  expiration: '365d'

- url: /.*
  script: djangoappengine/main/main.py

libraries:
- name: PIL
  version: "1.1.7"

