runtime: python27
api_version: 1
threadsafe: no

builtins:
- remote_api: on

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py

- url: /_ah/queue/deferred
  script: vendor/djangoappengine/deferred/handler.py

- url: /media/admin
  static_dir: vendor/django/contrib/admin/static
  expiration: '0'

- url: /static
  static_dir: static/
  expiration: '365d'
  secure: always

- url: /.*
  script: vendor/djangoappengine/main/main.py
  secure: always

libraries:
- name: PIL
  version: "1.1.7"

